name: Build docker images for release

on:
  release:
    types: [created, edited]


jobs:

  build_amd64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the AMD64 Docker image
      run: docker build . --file Dockerfile.amd64 --tag meowcoinproject/meowcoincore-api:amd64-$(date +%Y%m%d)

    - name: Push the AMD64 Docker image
      run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push meowcoinproject/meowcoincore-api:amd64-$(date +%Y%m%d)
          docker tag meowcoinproject/meowcoincore-api:amd64-$(date +%Y%m%d) meowcoinproject/meowcoincore-api:amd64-latest
          docker push meowcoinproject/meowcoincore-api:amd64-latest

  build_arm32v7:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update docker version
      run: |
          sudo apt-get -y remove docker docker-engine docker.io containerd runc
          sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get -y install docker-ce docker-ce-cli containerd.io
          export DOCKER_BUILDKIT=1
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
          docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64

    - name: Build the ARM32v7 Docker image
      run: docker build . --file Dockerfile.arm32v7 --tag meowcoinproject/meowcoincore-api:arm32v7-$(date +%Y%m%d)

    - name: Push the ARM32v7 Docker image
      run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push meowcoinproject/meowcoincore-api:arm32v7-$(date +%Y%m%d)
          docker tag meowcoinproject/meowcoincore-api:arm32v7-$(date +%Y%m%d) meowcoinproject/meowcoincore-api:arm32v7-latest
          docker push meowcoinproject/meowcoincore-api:arm32v7-latest
